version: '3.8'

services:
  jupyter:
    image: pmpi-inventory-predictor:latest
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
      - ./src:/src